image: lilianarago/epitest-docker-boost-sfml:latest

stages:
  - build
  - test
  - docs

before_script:
  - conan remote add conan-center https://api.bintray.com/conan/conan/conan-center -f
  - conan remote add epitech https://api.bintray.com/conan/epitech/public-conan -f
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan -f

build-binaries-linux:
  stage: build
  cache:
    key: rtypeEldriannConanData
    paths:
      - /root/.conan/data/
  script:
    - rm -rf build
    - mkdir build
    - cd build
    - conan install .. --build missing
    - cmake .. -G "Unix Makefiles"
    - cmake --build . --config Release
  artifacts:
    paths:
      - build/bin/r-type_client
      - build/bin/r-type_server

run-tests:
  stage: test
  cache:
    key: rtypeEldriannConanData
    paths:
      - /root/.conan/data/
  script:
    - rm -rf build
    - mkdir build
    - cd build
    - conan install .. --build missing
    - cmake .. -G "Unix Makefiles"
    - cmake --build . --config Release
    - make tests_run

rfc:
  stage: docs
  script:
    - ./scripts/generate_rfc.sh
    - cat rfc69420
  artifacts:
    paths:
      - docs/rfc69420
      - docs/rfc69420.html

uml:
  stage: docs
  before_script:
    - dnf -y install plantuml graphviz
  script:
    - plantuml rtype.puml
  artifacts:
    paths:
      - rtype.png