image: epitechcontent/epitest-docker:latest

stages:
  - build
  - test
  - docs

before_script:
  - conan remote add conan-center https://bintray.com/conan/conan-center
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan remote add epitech https://api.bintray.com/conan/epitech/public-conan

build-binaries-linux:
  stage: build
  script:
    - mkdir build
    - cd build
    - conan install .. --build missing
    - cmake .. -G "Unix Makefiles"
    - cmake --build . --config Release

run-tests:
  stage: test
  script:
    - mkdir build
    - cd build
    - conan install .. --build missing
    - cmake .. -G "Unix Makefiles"
    - cmake --build . --config Release
    - make tests_run

rfc:
  stage: docs
  script:
    - cd docs
    - ./generate_rfc.sh
    - cat rfc69420
  artifacts:
    paths:
      - ./docs/rfc69420
      - ./docs/rfc69420.html