image: epitechcontent/epitest-docker:latest

stages:
  - build
  - test

before_script:
  - conan remote add conan-center https://api.bintray.com/conan/conan/conan-center -f
  - conan remote add epitech https://api.bintray.com/conan/epitech/public-conan -f
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan -f

build-binaries-linux:
  stage: build
  script:
    - mkdir build
    - cd build
    - conan install .. --build missing
    - cmake .. -G "Unix Makefiles"
    - cmake --build . --config Release

run-tests:
  stage: test
  script:
    - mkdir build
    - cd build
    - conan install .. --build missing
    - cmake .. -G "Unix Makefiles"
    - cmake --build . --config Release
    - make tests_run